### ISSUE TITLE
Copyright & dukungan python 3

### ISSUE THREAD

**Issue by rafeyu** [homina/pica#1]
Jujur, saya seneng proyek ini om :+1:  Enteng!

Tapi ada masalah nih yang menurut saya cukup mengganggu.

1. Copyright nya nama asli dong. Saya pengguna Gentoo dan siapa tahu besok saya minat bantu bikin ebuild-nya. Masak authornya saya tulis "Ef" doang? :smile: 

2. Buat python 3 error karena "print" nggak konsisten om. Di bagian situ (https://gist.github.com/rafeyu/ab27368f65c091edf710)

3. Gambar gak otomatis ke center. Bug ini terasa kalau pakai tiling wm (soalnya saya pake i3)

makasih om sebelumnya

**Comment by homina** [comment]
1. haha, oke copyright saya bnerin scepatnya. mudah2an release berikut bner
2. oh blum di convert ke 3, hehe, klo om pake python 3 secara default mungkin di /usr/bin/pica nya bisa di edit jadi python2 /usr/share/pica/main.py "$1", soalnya saya di arch juga gitu
3. iya nih, kmaren ga nemu cara dapetin size window dngan akurat, skarang udah ketemu, di release berikutnya ini udah di bnerin kok. makasi udah nyobain.

**Comment by rafeyu** [comment]
Sip :3
udah saya patch pake link di atas kok om. Jadi gak perlu dijalani pakai python2. :+1: 

sama-sama om
